# docker compose
version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: yourssu_inviter_db
    hostname: yourssu_inviter_mysql
    # 서비스 배포 및 실행 옵션
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: yourssu_inviter
      MYSQL_USER: root
      MYSQL_PASSWORD: soongsil12
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - yourssu_mysql_volume:/var/lib/mysql
      - ./table.sql:/docker-entrypoint-initdb.d/table.sql

# 도커 볼륨
volumes:
  yourssu_mysql_volume: